/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <Arduino.h>
#include "lprSnmpTutorial.h"

static int led[3];
static int sw[3];

static inline int ledPin (int n) {
  static int ledPins[] = { 0, 1, 2 };
  return ledPins[n];
}

static inline int swPin (int n) {
  static int swPins[] = { 3, 4, 5 };
  return swPins[n];
}

void isrSw (int i) {
  sw[i] = digitalRead (swPin (i)) == 0;
  DEBUGMSGTL ( ("lprSnmpTutorial", "sw%d change to %d\n", i + 1, sw[i]));
  // trap
  send_easy_trap (SNMP_TRAP_ENTERPRISESPECIFIC, 100 + i);
}

void isrSw1() {
  isrSw (0);
}

void isrSw2() {
  isrSw (1);
}

void isrSw3() {
  isrSw (2);
}

/** Initializes the lprSnmpTutorial module */
void
init_lprSnmpTutorial (void) {
  const oid led1_oid[] = { 1, 3, 6, 1, 4, 1, 52900, 1, 1, 1, 1 };
  const oid led2_oid[] = { 1, 3, 6, 1, 4, 1, 52900, 1, 1, 1, 2 };
  const oid led3_oid[] = { 1, 3, 6, 1, 4, 1, 52900, 1, 1, 1, 3 };
  const oid sw1_oid[] = { 1, 3, 6, 1, 4, 1, 52900, 1, 1, 2, 1 };
  const oid sw2_oid[] = { 1, 3, 6, 1, 4, 1, 52900, 1, 1, 2, 2 };
  const oid sw3_oid[] = { 1, 3, 6, 1, 4, 1, 52900, 1, 1, 2, 3 };

  DEBUGMSGTL ( ("lprSnmpTutorial", "Initializing\n"));

  for (int i = 0; i < 3; i++) {
    pinMode (ledPin (i), OUTPUT);
    digitalWrite (ledPin (i), HIGH);
    pinMode (swPin (i), INPUT_PULLUP);
  }
  attachInterrupt (swPin (0), isrSw1, CHANGE);
  attachInterrupt (swPin (1), isrSw2, CHANGE);
  attachInterrupt (swPin (2), isrSw3, CHANGE);

  netsnmp_register_scalar (
    netsnmp_create_handler_registration ("led1", handle_led1,
                                         led1_oid, OID_LENGTH (led1_oid),
                                         HANDLER_CAN_RWRITE
                                        ));
  netsnmp_register_scalar (
    netsnmp_create_handler_registration ("led2", handle_led2,
                                         led2_oid, OID_LENGTH (led2_oid),
                                         HANDLER_CAN_RWRITE
                                        ));
  netsnmp_register_scalar (
    netsnmp_create_handler_registration ("led3", handle_led3,
                                         led3_oid, OID_LENGTH (led3_oid),
                                         HANDLER_CAN_RWRITE
                                        ));
  netsnmp_register_scalar (
    netsnmp_create_handler_registration ("sw1", handle_sw1,
                                         sw1_oid, OID_LENGTH (sw1_oid),
                                         HANDLER_CAN_RONLY
                                        ));
  netsnmp_register_scalar (
    netsnmp_create_handler_registration ("sw2", handle_sw2,
                                         sw2_oid, OID_LENGTH (sw2_oid),
                                         HANDLER_CAN_RONLY
                                        ));
  netsnmp_register_scalar (
    netsnmp_create_handler_registration ("sw3", handle_sw3,
                                         sw3_oid, OID_LENGTH (sw3_oid),
                                         HANDLER_CAN_RONLY
                                        ));
}


int
handle_led (netsnmp_agent_request_info *reqinfo,
            netsnmp_request_info *requests,
            int i) {

  int ret;

  switch (reqinfo->mode) {

    case MODE_GET:
      snmp_set_var_typed_value (requests->requestvb, ASN_INTEGER,
                                (u_char *) &led[i],
                                sizeof (led[i]));
      DEBUGMSGTL ( ("lprSnmpTutorial", "led%d current value :  %d\n", i + 1, led[i]));
      break;

      /*
       * SET REQUEST
       *
       * multiple states in the transaction.  See:
       * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
       */
    case MODE_SET_RESERVE1:
      /* or you could use netsnmp_check_vb_type_and_size instead */
      ret = netsnmp_check_vb_type (requests->requestvb, ASN_INTEGER);
      if (ret != SNMP_ERR_NOERROR) {
        netsnmp_set_request_error (reqinfo, requests, ret);
        return SNMP_ERR_GENERR;
      }
      break;

    case MODE_SET_RESERVE2:
      break;

    case MODE_SET_FREE:
      break;

    case MODE_SET_ACTION:
      if ( (i < 0) || (i > 2)) {
        netsnmp_set_request_error (reqinfo, requests, -1);
        return SNMP_ERR_GENERR;
      }
      led[i] = * (requests->requestvb->val.integer);
      digitalWrite (ledPin (i), led[i] == 0 ? HIGH : LOW);
      DEBUGMSGTL ( ("lprSnmpTutorial", "led%d set now to %d\n", i + 1, led[i]));
      break;

    case MODE_SET_COMMIT:
      break;

    case MODE_SET_UNDO:
      break;

    default:
      /* we should never get here, so this is a really bad error */
      snmp_log (LOG_ERR, "unknown mode (%d) in handle_led%d\n", reqinfo->mode, i);
      return SNMP_ERR_GENERR;
  }

  return SNMP_ERR_NOERROR;
}

int
handle_led1 (netsnmp_mib_handler *handler,
             netsnmp_handler_registration *reginfo,
             netsnmp_agent_request_info   *reqinfo,
             netsnmp_request_info         *requests) {

  return handle_led (reqinfo, requests, 0);
}

int
handle_led2 (netsnmp_mib_handler *handler,
             netsnmp_handler_registration *reginfo,
             netsnmp_agent_request_info   *reqinfo,
             netsnmp_request_info         *requests) {

  return handle_led (reqinfo, requests, 1);
}

int
handle_led3 (netsnmp_mib_handler *handler,
             netsnmp_handler_registration *reginfo,
             netsnmp_agent_request_info   *reqinfo,
             netsnmp_request_info         *requests) {
  return handle_led (reqinfo, requests, 2);
}

int
handle_sw (netsnmp_agent_request_info *reqinfo,
           netsnmp_request_info *requests,
           int i) {
  switch (reqinfo->mode) {

    case MODE_GET:
      snmp_set_var_typed_value (requests->requestvb, ASN_INTEGER,
                                (u_char *) &sw[i],
                                sizeof (sw[i]));
      DEBUGMSGTL ( ("lprSnmpTutorial", "sw%d current value :  %d\n", i + 1, sw[i]));
      break;


    default:
      /* we should never get here, so this is a really bad error */
      snmp_log (LOG_ERR, "unknown mode (%d) in handle_sw%d\n", i + 1, reqinfo->mode);
      return SNMP_ERR_GENERR;
  }

  return SNMP_ERR_NOERROR;
}

int
handle_sw1 (netsnmp_mib_handler *handler,
            netsnmp_handler_registration *reginfo,
            netsnmp_agent_request_info   *reqinfo,
            netsnmp_request_info         *requests) {

  return handle_sw (reqinfo, requests, 0);
}

int
handle_sw2 (netsnmp_mib_handler *handler,
            netsnmp_handler_registration *reginfo,
            netsnmp_agent_request_info   *reqinfo,
            netsnmp_request_info         *requests) {

  return handle_sw (reqinfo, requests, 1);
}

int
handle_sw3 (netsnmp_mib_handler *handler,
            netsnmp_handler_registration *reginfo,
            netsnmp_agent_request_info   *reqinfo,
            netsnmp_request_info         *requests) {

  return handle_sw (reqinfo, requests, 2);
}
