/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef LPRSNMPTUTORIAL_H
#define LPRSNMPTUTORIAL_H

/* function declarations */
void init_lprSnmpTutorial(void);
Netsnmp_Node_Handler handle_led1;
Netsnmp_Node_Handler handle_led2;
Netsnmp_Node_Handler handle_led3;
Netsnmp_Node_Handler handle_sw1;
Netsnmp_Node_Handler handle_sw2;
Netsnmp_Node_Handler handle_sw3;

#endif /* LPRSNMPTUTORIAL_H */
