.PHONY: clean All

All:
	@echo "----------Building project:[ pointcast-agent - Debug ]----------"
	@"$(MAKE)" -f  "pointcast-agent.mk"
clean:
	@echo "----------Cleaning project:[ pointcast-agent - Debug ]----------"
	@"$(MAKE)" -f  "pointcast-agent.mk" clean
